// Generated by the Unreal -> Unity converter. Edits are overwritten on rebuild.
// Source: /Game/Test/M_EngineFuncs
// Unreal master material, 7 nodes in the graph
Shader "UassetConverted/engine_functions"
{
    Properties
    {
        _Base("Base", 2D) = "white" {}
        _Normala("NormalA", 2D) = "bump" {}
        _Normalb("NormalB", 2D) = "bump" {}
        [HideInInspector] _Cutoff("Alpha Cutoff", Range(0, 1)) = 0.333
        [HideInInspector] _Cull("Cull", Float) = 2
    }

    SubShader
    {
        Tags
        {
            "RenderType" = "Opaque"
            "RenderPipeline" = "UniversalPipeline"
            "Queue" = "Geometry"
        }
        LOD 300

        HLSLINCLUDE
        #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

        CBUFFER_START(UnityPerMaterial)
            float4 _Base_ST;
            float4 _Normala_ST;
            float4 _Normalb_ST;
            float _Cutoff;
            float _Cull;
        CBUFFER_END

        TEXTURE2D(_Base);
        SAMPLER(sampler_Base);
        TEXTURE2D(_Normala);
        SAMPLER(sampler_Normala);
        TEXTURE2D(_Normalb);
        SAMPLER(sampler_Normalb);

// --- Material functions carried over from Unreal ---

// Engine_MaterialFunctions02/Utility/BlendAngleCorrectedNormals
// Reoriented Normal Mapping, the way the Unreal node does it.
float3 BlendAngleCorrectedNormals(float3 BaseNormal, float3 AdditionalNormal)
{
    BaseNormal.b += 1.0;
    AdditionalNormal *= float3(-1.0, -1.0, 1.0);
    return BaseNormal * dot(BaseNormal, AdditionalNormal) / max(BaseNormal.b, 1e-5) - AdditionalNormal;
}

// Engine_MaterialFunctions01/ImageAdjustment/CheapContrast
float CheapContrast(float In, float Contrast)
{
    return saturate(lerp(0.0 - Contrast, 1.0 + Contrast, In));
}

float3 CheapContrast_RGB(float3 In, float Contrast)
{
    return saturate(lerp((0.0 - Contrast).xxx, (1.0 + Contrast).xxx, In));
}

// Unreal Desaturation node
float3 UEDesaturation(float3 In, float Fraction, float3 LuminanceFactors)
{
    return lerp(In, dot(In, LuminanceFactors).xxx, Fraction);
}


        struct SurfaceValues
        {
            float3 albedo;
            float  metallic;
            float  smoothness;
            float3 emission;
            float3 normalTS;
            float  occlusion;
            float  alpha;
        };

        struct SurfaceInputs
        {
            float2 uv0;
        };

        SurfaceValues EvaluateSurface(SurfaceInputs IN)
        {
            SurfaceValues surface;
            float4 n1 = SAMPLE_TEXTURE2D(_Base, sampler_Base, IN.uv0);  // sample _Base
            float3 n2 = CheapContrast_RGB((n1).rgb, 0.2);  // CheapContrast_RGB
            float3 n3 = UEDesaturation(n2, 0.3, float3(0.3, 0.59, 0.11));  // Desaturation
            float n4 = CheapContrast((n1).r, 0.4);  // CheapContrast
            float4 n5 = float4(UnpackNormal(SAMPLE_TEXTURE2D(_Normala, sampler_Normala, IN.uv0)), 1.0);  // sample _Normala (normal)
            float4 n6 = float4(UnpackNormal(SAMPLE_TEXTURE2D(_Normalb, sampler_Normalb, IN.uv0)), 1.0);  // sample _Normalb (normal)
            float3 n7 = BlendAngleCorrectedNormals((n5).rgb, (n6).rgb);  // BlendAngleCorrectedNormals
            surface.albedo     = n3;
            surface.metallic   = saturate(0);
            // Unreal stores roughness, Unity wants smoothness — this is the inversion.
            surface.smoothness = saturate(1.0 - (n4));
            surface.emission   = float3(0, 0, 0);
            surface.normalTS   = n7;
            surface.occlusion  = saturate(1);
            surface.alpha      = saturate(1.0);
            return surface;
        }
        ENDHLSL

        Pass
        {
            Name "ForwardLit"
            Tags { "LightMode" = "UniversalForward" }

            Blend Off
            ZWrite On
            Cull [_Cull]

            HLSLPROGRAM
            #pragma vertex ForwardVertex
            #pragma fragment ForwardFragment
            #pragma target 3.0

            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN
            #pragma multi_compile _ _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS
            #pragma multi_compile_fragment _ _ADDITIONAL_LIGHT_SHADOWS
            #pragma multi_compile_fragment _ _SHADOWS_SOFT
            #pragma multi_compile_fragment _ _SCREEN_SPACE_OCCLUSION
            #pragma multi_compile _ LIGHTMAP_ON
            #pragma multi_compile _ DIRLIGHTMAP_COMBINED
            #pragma multi_compile _ LIGHTMAP_SHADOW_MIXING
            #pragma multi_compile _ SHADOWS_SHADOWMASK
            #pragma multi_compile_fog
            #pragma multi_compile_instancing

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"

            struct Attributes
            {
                float4 positionOS : POSITION;
                float3 normalOS   : NORMAL;
                float4 tangentOS  : TANGENT;
                float2 uv0        : TEXCOORD0;
                float2 staticLightmapUV : TEXCOORD1;
                float4 color      : COLOR;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };

            struct Varyings
            {
                float4 positionCS  : SV_POSITION;
                float3 positionWS  : TEXCOORD0;
                float3 normalWS    : TEXCOORD1;
                float4 tangentWS   : TEXCOORD2;
                float2 uv0         : TEXCOORD3;
                float4 color       : COLOR;
                DECLARE_LIGHTMAP_OR_SH(staticLightmapUV, vertexSH, 8);
                float  fogFactor   : TEXCOORD9;
                UNITY_VERTEX_INPUT_INSTANCE_ID
                UNITY_VERTEX_OUTPUT_STEREO
            };

            Varyings ForwardVertex(Attributes input)
            {
                Varyings output = (Varyings)0;
                UNITY_SETUP_INSTANCE_ID(input);
                UNITY_TRANSFER_INSTANCE_ID(input, output);
                UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(output);

                VertexPositionInputs positions = GetVertexPositionInputs(input.positionOS.xyz);
                VertexNormalInputs normals = GetVertexNormalInputs(input.normalOS, input.tangentOS);

                output.positionCS = positions.positionCS;
                output.positionWS = positions.positionWS;
                output.normalWS   = normals.normalWS;
                output.tangentWS  = float4(normals.tangentWS, input.tangentOS.w * GetOddNegativeScale());
                output.uv0 = input.uv0;
                output.color = input.color;
                OUTPUT_LIGHTMAP_UV(input.staticLightmapUV, unity_LightmapST, output.staticLightmapUV);
                OUTPUT_SH(normals.normalWS, output.vertexSH);
                output.fogFactor = ComputeFogFactor(positions.positionCS.z);
                return output;
            }

            half4 ForwardFragment(Varyings input, half facing : VFACE) : SV_Target
            {
                UNITY_SETUP_INSTANCE_ID(input);
                UNITY_SETUP_STEREO_EYE_INDEX_POST_VERTEX(input);

                SurfaceInputs surfaceInputs = (SurfaceInputs)0;
                surfaceInputs.uv0 = input.uv0;
                SurfaceValues surface = EvaluateSurface(surfaceInputs);

                InputData inputData = (InputData)0;
                inputData.positionWS = input.positionWS;

                float sgn = input.tangentWS.w;
                float3 bitangent = sgn * cross(input.normalWS.xyz, input.tangentWS.xyz);
                half3x3 tangentToWorld = half3x3(input.tangentWS.xyz, bitangent, input.normalWS.xyz);
                inputData.tangentToWorld = tangentToWorld;
                inputData.normalWS = NormalizeNormalPerPixel(TransformTangentToWorld(surface.normalTS, tangentToWorld));

                inputData.viewDirectionWS = SafeNormalize(GetCameraPositionWS() - input.positionWS);
                inputData.shadowCoord = TransformWorldToShadowCoord(input.positionWS);
                inputData.fogCoord = input.fogFactor;
                inputData.vertexLighting = half3(0, 0, 0);
                inputData.bakedGI = SAMPLE_GI(input.staticLightmapUV, input.vertexSH, inputData.normalWS);
                inputData.normalizedScreenSpaceUV = GetNormalizedScreenSpaceUV(input.positionCS);
                inputData.shadowMask = SAMPLE_SHADOWMASK(input.staticLightmapUV);

                SurfaceData surfaceData = (SurfaceData)0;
                surfaceData.albedo     = surface.albedo;
                surfaceData.metallic   = surface.metallic;
                surfaceData.smoothness = surface.smoothness;
                surfaceData.normalTS   = surface.normalTS;
                surfaceData.emission   = surface.emission;
                surfaceData.occlusion  = surface.occlusion;
                surfaceData.alpha      = surface.alpha;
                surfaceData.specular   = half3(0, 0, 0);
                surfaceData.clearCoatMask = 0;
                surfaceData.clearCoatSmoothness = 0;

                half4 color = UniversalFragmentPBR(inputData, surfaceData);
                color.rgb = MixFog(color.rgb, inputData.fogCoord);
                color.a = 1.0;
                return color;
            }
            ENDHLSL
        }

        Pass
        {
            Name "ShadowCaster"
            Tags { "LightMode" = "ShadowCaster" }
            ZWrite On
            ZTest LEqual
            ColorMask 0
            Cull [_Cull]

            HLSLPROGRAM
            #pragma vertex ShadowVertex
            #pragma fragment ShadowFragment
            #pragma multi_compile_vertex _ _CASTING_PUNCTUAL_LIGHT_SHADOW

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Shadows.hlsl"

            float3 _LightDirection;
            float3 _LightPosition;

            struct ShadowAttributes
            {
                float4 positionOS : POSITION;
                float3 normalOS   : NORMAL;
                float2 uv0        : TEXCOORD0;
                float4 color      : COLOR;
            };

            struct ShadowVaryings
            {
                float4 positionCS : SV_POSITION;
                float2 uv0         : TEXCOORD3;
                float4 color      : COLOR;
                float3 positionWS : TEXCOORD8;
                float3 normalWS   : TEXCOORD9;
            };

            ShadowVaryings ShadowVertex(ShadowAttributes input)
            {
                ShadowVaryings output = (ShadowVaryings)0;
                float3 positionWS = TransformObjectToWorld(input.positionOS.xyz);
                float3 normalWS = TransformObjectToWorldNormal(input.normalOS);

                #if _CASTING_PUNCTUAL_LIGHT_SHADOW
                    float3 lightDirectionWS = normalize(_LightPosition - positionWS);
                #else
                    float3 lightDirectionWS = _LightDirection;
                #endif

                output.positionCS = TransformWorldToHClip(ApplyShadowBias(positionWS, normalWS, lightDirectionWS));
                #if UNITY_REVERSED_Z
                    output.positionCS.z = min(output.positionCS.z, UNITY_NEAR_CLIP_VALUE);
                #else
                    output.positionCS.z = max(output.positionCS.z, UNITY_NEAR_CLIP_VALUE);
                #endif
                output.uv0 = input.uv0;
                output.color = input.color;
                output.positionWS = positionWS;
                output.normalWS = normalWS;
                return output;
            }

            half4 ShadowFragment(ShadowVaryings input) : SV_Target
            {
                SurfaceInputs surfaceInputs = (SurfaceInputs)0;
                surfaceInputs.uv0 = input.uv0;
                SurfaceValues surface = EvaluateSurface(surfaceInputs);

                return 0;
            }
            ENDHLSL
        }

        Pass
        {
            Name "DepthOnly"
            Tags { "LightMode" = "DepthOnly" }
            ZWrite On
            ColorMask R
            Cull [_Cull]

            HLSLPROGRAM
            #pragma vertex DepthOnlyVertex
            #pragma fragment DepthOnlyFragment

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"

            struct DepthOnlyAttributes
            {
                float4 positionOS : POSITION;
                float3 normalOS   : NORMAL;
                float2 uv0        : TEXCOORD0;
                float4 color      : COLOR;
            };

            struct DepthOnlyVaryings
            {
                float4 positionCS : SV_POSITION;
                float2 uv0         : TEXCOORD3;
                float4 color      : COLOR;
                float3 positionWS : TEXCOORD8;
                float3 normalWS   : TEXCOORD9;
            };

            DepthOnlyVaryings DepthOnlyVertex(DepthOnlyAttributes input)
            {
                DepthOnlyVaryings output = (DepthOnlyVaryings)0;
                output.positionCS = TransformObjectToHClip(input.positionOS.xyz);
                output.uv0 = input.uv0;
                output.color = input.color;
                output.positionWS = TransformObjectToWorld(input.positionOS.xyz);
                output.normalWS = TransformObjectToWorldNormal(input.normalOS);
                return output;
            }

            half4 DepthOnlyFragment(DepthOnlyVaryings input) : SV_Target
            {
                SurfaceInputs surfaceInputs = (SurfaceInputs)0;
                surfaceInputs.uv0 = input.uv0;
                SurfaceValues surface = EvaluateSurface(surfaceInputs);

                return 0;
            }
            ENDHLSL
        }

        Pass
        {
            Name "Meta"
            Tags { "LightMode" = "Meta" }
            Cull Off

            HLSLPROGRAM
            #pragma vertex MetaPassVertex
            #pragma fragment MetaPassFragment
            #pragma target 3.0

            #pragma multi_compile_fragment _ EDITOR_VISUALIZATION

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/MetaInput.hlsl"

            struct MetaAttributes
            {
                float4 positionOS : POSITION;
                float3 normalOS   : NORMAL;
                float2 uv0        : TEXCOORD0;
                float2 staticLightmapUV : TEXCOORD1;
                float2 dynamicLightmapUV : TEXCOORD2;
                float4 color      : COLOR;
            };

            struct MetaVaryings
            {
                float4 positionCS : SV_POSITION;
                float2 uv0         : TEXCOORD3;
                float4 color      : COLOR;
                float3 positionWS : TEXCOORD10;
                float3 normalWS   : TEXCOORD11;
            #ifdef EDITOR_VISUALIZATION
                float2 vizUV      : TEXCOORD12;
                float4 lightCoord : TEXCOORD13;
            #endif
            };

            MetaVaryings MetaPassVertex(MetaAttributes input)
            {
                MetaVaryings output = (MetaVaryings)0;
                output.positionCS = UnityMetaVertexPosition(input.positionOS.xyz, input.staticLightmapUV, input.dynamicLightmapUV, unity_LightmapST, unity_DynamicLightmapST);
                output.uv0 = input.uv0;
                output.color = input.color;
                output.positionWS = TransformObjectToWorld(input.positionOS.xyz);
                output.normalWS = TransformObjectToWorldNormal(input.normalOS);
            #ifdef EDITOR_VISUALIZATION
                UnityEditorVizData(input.positionOS.xyz, input.uv0, input.staticLightmapUV, input.dynamicLightmapUV, output.vizUV, output.lightCoord);
            #endif
                return output;
            }

            half4 MetaPassFragment(MetaVaryings input) : SV_Target
            {
                SurfaceInputs surfaceInputs = (SurfaceInputs)0;
                surfaceInputs.uv0 = input.uv0;
                SurfaceValues surface = EvaluateSurface(surfaceInputs);

                MetaInput metaInput = (MetaInput)0;
                metaInput.Albedo     = surface.albedo;
                metaInput.Emission   = surface.emission;
            #ifdef EDITOR_VISUALIZATION
                metaInput.VizUV      = input.vizUV;
                metaInput.LightCoord = input.lightCoord;
            #endif
                return UnityMetaFragment(metaInput);
            }
            ENDHLSL
        }
    }

    FallBack "Universal Render Pipeline/Lit"
}
